import {agentSchema,agentIssue} from '@/lib/agent-schema';

/** Active agents per account, and all agents including archived ones (archiving frees an active slot). */
const MAX_ACTIVE=50,MAX_TOTAL=200;
import {context,failure,body,HttpError} from '@/lib/server';
import {MAX_PRICE,MIN_PRICE} from '@/lib/economy';
export async function POST(request:Request){try{const {db,owner}=await context(request,true);const p=agentSchema.safeParse(await body(request));if(!p.success)throw new HttpError(400,agentIssue(p.error));const config=p.data;const id=config.id||crypto.randomUUID();const existing=await db.prepare('SELECT owner,archived FROM agents WHERE id=?').bind(id).first<{owner:string;archived:number}>();if(existing&&existing.owner!==owner)throw new HttpError(404,'Agent not found.');
 // saving from the Studio makes the agent active again, so a restore also needs a free active slot
 const count=await db.prepare('SELECT count(*) AS n, SUM(CASE WHEN archived=0 THEN 1 ELSE 0 END) AS active FROM agents WHERE owner=?').bind(owner).first<{n:number;active:number|null}>();
 if(!existing&&(count?.n??0)>=MAX_TOTAL)throw new HttpError(400,`You have ${MAX_TOTAL} agents including archived ones, the most this preview keeps.`);
 if((!existing||existing.archived)&&(count?.active??0)>=MAX_ACTIVE)throw new HttpError(400,`You can have up to ${MAX_ACTIVE} active agents. Archive one in My agents first.`);const updated=new Date().toISOString();await db.prepare('INSERT INTO agents (id,owner,name,config,updated,archived) VALUES (?,?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET name=excluded.name,config=excluded.config,updated=excluded.updated,archived=0 WHERE agents.owner=excluded.owner').bind(id,owner,config.name,JSON.stringify(config),updated).run();const meta=await db.prepare('SELECT published,price,uses FROM agents WHERE id=?').bind(id).first<{published:number;price:number;uses:number}>();return Response.json({...config,id,updated,archived:0,published:meta?.published??0,price:meta?.price??0,uses:meta?.uses??0});}catch(e){return failure(e)}}
export async function PATCH(request:Request){try{const {db,owner}=await context(request,true);const data=await body(request);if(typeof data.id!=='string')throw new HttpError(400,'Invalid agent update.');const now=new Date().toISOString();
 if(typeof data.archived==='boolean'){
  if(!data.archived){const c=await db.prepare('SELECT count(*) AS n FROM agents WHERE owner=? AND archived=0').bind(owner).first<{n:number}>();if((c?.n??0)>=MAX_ACTIVE)throw new HttpError(400,`You can have up to ${MAX_ACTIVE} active agents. Archive one first.`);}
  const result=await db.prepare('UPDATE agents SET archived=?,published=CASE WHEN ?=1 THEN 0 ELSE published END,updated=? WHERE id=? AND owner=?').bind(data.archived?1:0,data.archived?1:0,now,data.id,owner).run();if(!result.meta.changes)throw new HttpError(404,'Agent not found.');return Response.json({ok:true});}
 if(typeof data.published==='boolean'){const price=data.price===undefined?undefined:Number(data.price);if(price!==undefined&&(!Number.isInteger(price)||price<MIN_PRICE||price>MAX_PRICE))throw new HttpError(400,`Price must be a whole number between ${MIN_PRICE} and ${MAX_PRICE} credits.`);
  // the price of one chat message on the agent's page, apart from the price of a task (drizzle/0026); left out = unchanged
  const talkPrice=data.talkPrice===undefined?undefined:Number(data.talkPrice);if(talkPrice!==undefined&&(!Number.isInteger(talkPrice)||talkPrice<MIN_PRICE||talkPrice>MAX_PRICE))throw new HttpError(400,`The chat price must be a whole number between ${MIN_PRICE} and ${MAX_PRICE} credits.`);
  const result=await db.prepare('UPDATE agents SET published=?,price=COALESCE(?,price),talk_price=COALESCE(?,talk_price),published_at=CASE WHEN ?=1 AND published_at IS NULL THEN ? ELSE published_at END,updated=? WHERE id=? AND owner=? AND archived=0').bind(data.published?1:0,price??null,talkPrice??null,data.published?1:0,now,now,data.id,owner).run();if(!result.meta.changes)throw new HttpError(404,'Agent not found.');return Response.json({ok:true,published:data.published,price,talkPrice});}
 throw new HttpError(400,'Invalid agent update.');}catch(e){return failure(e)}}
