// @ts-nocheck
/* GENERATED by scripts/build-harvex-engine.mjs from lib/harvex3d/src — edit the sources, then rebuild. */
/** Installs presets, wardrobe options, motion groups and powers on G.HARVEX. Safe on the server (no three.js). */
export function installData(G) {
/* Harvex — roster, wardrobe options, motions & skills metadata. */
(function (G) {
'use strict';
const R = G.HARVEX;
const h = (o) => o; // readability
// skin tones (light → deep)
const SK = ['#f3d2b8', '#e8b894', '#d49a72', '#b97a52', '#8e5a3b', '#6a4029', '#4a2b1d'];
const HAIR = ['#1b1512', '#3a2a22', '#6b4a33', '#a5733f', '#d9b27a', '#e8e2d6', '#ffe600', '#ff7eb6', '#7aa7ff', '#b28dff'];

R.WARDROBE = {
  body: [['feminine', 'Feminine'], ['masculine', 'Masculine']],
  build: [['slim', 'Slim'], ['regular', 'Regular'], ['curvy', 'Curvy'], ['broad', 'Broad']],
  hair: [['short', 'Short'], ['swept', 'Swept'], ['buzz', 'Buzz'], ['spiky', 'Spiky'], ['curly', 'Curly'], ['afro', 'Afro'], ['bob', 'Bob'], ['long', 'Long'], ['ponytail', 'Ponytail'], ['twintails', 'Twin tails'], ['bun', 'Bun'], ['mohawk', 'Mohawk'], ['none', 'None']],
  facial: [['none', 'None'], ['stubble', 'Stubble'], ['beard', 'Beard']],
  top: [['tee', 'T-shirt'], ['tank', 'Tank top'], ['sweater', 'Sweater'], ['hoodie', 'Hoodie'], ['tracksuit', 'Track jacket'], ['bomber', 'Flight jacket'], ['jacket', 'Open jacket'], ['suit', 'Suit'], ['coat', 'Long coat'], ['robe', 'Robe'], ['armor', 'Armor'], ['spacesuit', 'Spacesuit']],
  bottom: [['pants', 'Pants'], ['joggers', 'Joggers'], ['cargo', 'Cargo'], ['shorts', 'Shorts'], ['skirt', 'Skirt']],
  legwear: [['bare', 'Bare legs'], ['tights', 'Tights']],
  shoes: [['sneaker', 'Sneakers'], ['boot', 'Boots'], ['loafer', 'Loafers']],
  head: [['none', 'None'], ['cap', 'Cap'], ['beanie', 'Beanie'], ['hat', 'Explorer hat'], ['headphones', 'Headphones'], ['halo', 'Halo'], ['ears', 'Cat ears'], ['helmet', 'Space helmet']],
  face: [['none', 'None'], ['glasses', 'Glasses'], ['shades', 'Shades'], ['visor', 'Visor']],
  back: [['none', 'None'], ['backpack', 'Backpack'], ['jetpack', 'Jetpack'], ['cape', 'Cape'], ['scarf', 'Scarf']],
  finish: [['matte', 'Matte'], ['gloss', 'Gloss']],
  swatches: ['#ffe600', '#1f2528', '#2b3a33', '#f1efe6', '#9b73dd', '#4fb6ca', '#ec89b7', '#e0664f', '#f2b84b', '#466dcc', '#356f69', '#a58f55', '#7487a8', '#6b3fa0'],
  skin: SK, hairColors: HAIR,
  eyes: ['#4a3526', '#2d5d8a', '#3f7a4a', '#7a5a2a', '#5a5a66', '#8a3fa0'],
  glow: ['#ffe600', '#5ee0ff', '#ff6fb1', '#ffd25e', '#b28dff', '#ff8a4c'],
};

const P = [];
const hu = (id, name, role, desc, sig, look) => P.push({ id, name, role, desc, sig, cat: 'Humanoid', look: Object.assign({ kind: 'human' }, look) });
const co = (id, name, role, desc, sig, look) => P.push({ id, name, role, desc, sig, cat: 'Companion', look: Object.assign({ kind: 'companion', model: id }, look) });

// original 9 humanoids, kept by id so saved agents still open
hu('atlas', 'Dorian', 'ORGANIZER', 'Pressed suit, level tone, says it once.', 'scan', { body: 'masculine', build: 'regular', skin: SK[2], hair: { style: 'swept', color: HAIR[1] }, facial: 'stubble', top: { type: 'suit', color: '#1f2428', accent: '#ffe600' }, bottom: { type: 'pants', color: '#1a1e21' }, shoes: { type: 'loafer', color: '#141414' }, face: 'none', eyes: '#3a2a20' });
hu('nova', 'Pippa', 'SKETCHER', 'Bomber jacket and a sketchbook that is never empty.', 'hype', { body: 'feminine', build: 'slim', skin: SK[1], hair: { style: 'bob', color: '#2a1c1a' }, top: { type: 'bomber', color: '#9b73dd', accent: '#ffe600' }, bottom: { type: 'joggers', color: '#2b2440' }, shoes: { type: 'sneaker', color: '#f1efe6' }, eyes: '#5a3a2a' });
hu('orbit', 'Magnus', 'PATHFINDER', 'Dressed for the questions nobody has charted yet.', 'levitate', { body: 'masculine', build: 'regular', skin: SK[3], hair: { style: 'short', color: HAIR[0] }, top: { type: 'spacesuit', color: '#e3e8e4', accent: '#ffe600' }, bottom: { type: 'pants', color: '#e3e8e4' }, head: 'helmet', back: 'none', eyes: '#3a2a20' });
hu('kira', 'Odile', 'PLANNER', 'A long coat, and five moves already planned.', 'shield', { body: 'feminine', build: 'slim', skin: SK[0], hair: { style: 'long', color: '#1e1714' }, top: { type: 'coat', color: '#356f69', accent: '#e9d9a8' }, bottom: { type: 'pants', color: '#1b2624' }, shoes: { type: 'boot', color: '#1d1a18' }, eyes: '#2d5d8a' });
hu('dash', 'Remy', 'SPRINTER', 'Has started on the task before you finish asking.', 'blink', { body: 'masculine', build: 'regular', skin: SK[4], hair: { style: 'buzz', color: HAIR[0] }, top: { type: 'tracksuit', color: '#466dcc', accent: '#f1efe6' }, bottom: { type: 'joggers', color: '#466dcc' }, shoes: { type: 'sneaker', color: '#ffe600' }, eyes: '#3a2a20' });
// (byte, scout, maker and guardian were an android and three bots; the user asked for people only, 6 Oct 2026. The ids
// and names stay, so saved agents keep working; a saved look that says kind 'companion' still draws its bot.)
hu('byte', 'Hugo', 'ENGINEER', 'Opens things up to see how they work, then keeps going.', 'orb', { body: 'masculine', build: 'slim', skin: SK[2], eyes: '#2d5d8a', hair: { style: 'spiky', color: '#1b1512' }, top: { type: 'hoodie', color: '#ffe600', accent: '#2a302c' }, bottom: { type: 'joggers', color: '#3a4540' }, shoes: { type: 'sneaker', color: '#2a302c' }, head: 'headphones', glow: '#5ee0ff' });
hu('echo', 'Suki', 'PRODUCER', 'Works with music on and lands every beat.', 'hype', { body: 'feminine', build: 'curvy', skin: SK[2], hair: { style: 'ponytail', color: '#3b1f2a' }, top: { type: 'hoodie', color: '#d2759b', accent: '#f1efe6' }, bottom: { type: 'joggers', color: '#2a2226' }, shoes: { type: 'sneaker', color: '#f1efe6' }, head: 'headphones', accColor: '#1f2327', eyes: '#4a3526', glow: '#ff6fb1' });
hu('terra', 'Bram', 'REPORTER', 'Worn boots, a full notebook, sources you can check.', 'scan', { body: 'masculine', build: 'regular', skin: SK[3], hair: { style: 'short', color: HAIR[2] }, facial: 'beard', top: { type: 'jacket', color: '#a58f55', accent: '#6b4a33' }, bottom: { type: 'cargo', color: '#5d5236' }, shoes: { type: 'boot', color: '#4a3526' }, head: 'hat', back: 'backpack', accColor: '#6b4a33', eyes: '#3f7a4a', glow: '#ffd25e' });
hu('volt', 'Gideon', 'WATCHMAN', 'Built like a wall and quicker than he looks.', 'shield', { body: 'masculine', build: 'broad', skin: SK[5], hair: { style: 'mohawk', color: '#ffe600' }, top: { type: 'armor', color: '#2c343c', accent: '#7487a8' }, bottom: { type: 'cargo', color: '#2c343c' }, shoes: { type: 'boot', color: '#1d2126' }, eyes: '#4a3526' });
// new humanoids
hu('vesper', 'Elodie', 'ARTIST', 'Finds the layout hiding inside a rough idea.', 'hype', { body: 'feminine', build: 'curvy', skin: SK[5], hair: { style: 'afro', color: '#1b1512' }, top: { type: 'tee', color: '#f2b84b', accent: '#1f2528' }, bottom: { type: 'skirt', color: '#1f2528' }, legwear: 'tights', shoes: { type: 'sneaker', color: '#f1efe6' }, face: 'glasses', accColor: '#e0664f', eyes: '#4a3526', glow: '#ffd25e' });
hu('rook', 'Tobin', 'DRAFTER', 'Has a first version ready by midday.', 'orb', { body: 'masculine', build: 'regular', skin: SK[3], hair: { style: 'spiky', color: '#1b1512' }, top: { type: 'hoodie', color: '#2b3a33', accent: '#ffe600' }, bottom: { type: 'joggers', color: '#1f2528' }, shoes: { type: 'sneaker', color: '#e0664f' }, head: 'cap', accColor: '#ffe600', eyes: '#3a2a20' });
hu('mira', 'Anouk', 'AUDITOR', 'Hand her a tangle of figures, get one clear answer back.', 'scan', { body: 'feminine', build: 'slim', skin: SK[1], hair: { style: 'twintails', color: '#7aa7ff' }, top: { type: 'sweater', color: '#f1efe6', accent: '#7aa7ff' }, bottom: { type: 'skirt', color: '#466dcc' }, legwear: 'bare', shoes: { type: 'loafer', color: '#2a1f1a' }, eyes: '#2d5d8a', glow: '#5ee0ff' });
hu('juno', 'Marlow', 'PRESENTER', 'Ready to present, slides already open.', 'shield', { body: 'feminine', build: 'curvy', skin: SK[4], hair: { style: 'bun', color: '#2a1c1a' }, top: { type: 'suit', color: '#e3ddd0', accent: '#e0664f' }, bottom: { type: 'pants', color: '#e3ddd0' }, shoes: { type: 'loafer', color: '#e0664f' }, face: 'shades', eyes: '#4a3526', glow: '#ff8a4c' });
hu('cole', 'Ansel', 'BROKER', 'Eyes on the numbers, pulse steady.', 'blink', { body: 'masculine', build: 'broad', skin: SK[2], hair: { style: 'short', color: '#1b1512' }, facial: 'stubble', top: { type: 'tank', color: '#1f2528', accent: '#ffe600' }, bottom: { type: 'shorts', color: '#356f69' }, shoes: { type: 'sneaker', color: '#1f2528' }, back: 'scarf', accColor: '#ffe600', eyes: '#3a2a20' });
hu('lumi', 'Thea', 'THINKER', 'Soft-spoken, and always asks the question after yours.', 'levitate', { body: 'feminine', build: 'slim', skin: SK[0], hair: { style: 'long', color: '#e8e2d6' }, top: { type: 'robe', color: '#f1efe6', accent: '#b28dff' }, bottom: { type: 'pants', color: '#f1efe6' }, shoes: { type: 'loafer', color: '#b28dff' }, head: 'halo', eyes: '#8a3fa0', glow: '#b28dff' });
hu('otto', 'Gus', 'RANGER', 'Loud laugh, heavy pack, knows the way.', 'shield', { body: 'masculine', build: 'broad', skin: SK[4], hair: { style: 'curly', color: '#1b1512' }, facial: 'beard', top: { type: 'jacket', color: '#e0664f', accent: '#1f2528' }, bottom: { type: 'cargo', color: '#3a4540' }, shoes: { type: 'boot', color: '#3a2a22' }, back: 'backpack', accColor: '#2b3a33', eyes: '#4a3526', glow: '#ff8a4c' });
hu('wren', 'Calla', 'NARRATOR', 'Makes a summary you want to read to the end.', 'hype', { body: 'feminine', build: 'slim', skin: SK[2], hair: { style: 'long', color: '#3a2a22' }, top: { type: 'bomber', color: '#ec89b7', accent: '#f1efe6' }, bottom: { type: 'skirt', color: '#2b2440' }, legwear: 'tights', shoes: { type: 'boot', color: '#1f2528' }, head: 'ears', eyes: '#4a3526', glow: '#ff6fb1' });
hu('zara', 'Freya', 'VERIFIER', 'Believes a claim after the second check.', 'shield', { body: 'feminine', build: 'regular', skin: SK[6], hair: { style: 'bob', color: '#ff7eb6' }, top: { type: 'armor', color: '#f1efe6', accent: '#ec89b7' }, bottom: { type: 'pants', color: '#2b2440' }, shoes: { type: 'boot', color: '#f1efe6' }, eyes: '#4a3526', glow: '#ff6fb1' });
hu('felix', 'Jasper', 'MECHANIC', 'Strips a problem to its parts and puts it back improved.', 'orb', { body: 'masculine', build: 'regular', skin: SK[1], hair: { style: 'curly', color: '#a5733f' }, top: { type: 'tee', color: '#4fb6ca', accent: '#f1efe6' }, bottom: { type: 'cargo', color: '#a58f55' }, shoes: { type: 'sneaker', color: '#f2b84b' }, face: 'glasses', back: 'jetpack', accColor: '#1f2528', eyes: '#3f7a4a', glow: '#5ee0ff' });
hu('ines', 'Maren', 'READER', 'Goes through the small print and tells you what it says.', 'scan', { body: 'feminine', build: 'regular', skin: SK[1], hair: { style: 'bun', color: '#6b4a33' }, top: { type: 'coat', color: '#6b3fa0', accent: '#f2b84b' }, bottom: { type: 'pants', color: '#2b2440' }, shoes: { type: 'boot', color: '#2a1f1a' }, face: 'glasses', accColor: '#f2b84b', eyes: '#7a5a2a', glow: '#b28dff' });
hu('taro', 'Emil', 'EDITOR', 'Out of a hundred links, brings you the three worth opening.', 'blink', { body: 'masculine', build: 'slim', skin: SK[1], hair: { style: 'short', color: '#1b1512' }, top: { type: 'jacket', color: '#1f2528', accent: '#ffe600' }, bottom: { type: 'shorts', color: '#2b3a33' }, shoes: { type: 'sneaker', color: '#f1efe6' }, head: 'beanie', back: 'cape', accColor: '#ffe600', eyes: '#3a2a20' });
hu('noor', 'Inka', 'MAPMAKER', 'Draws the way from what you asked to what you need.', 'levitate', { body: 'feminine', build: 'curvy', skin: SK[3], hair: { style: 'ponytail', color: '#1b1512' }, top: { type: 'spacesuit', color: '#f1efe6', accent: '#ff8a4c' }, bottom: { type: 'pants', color: '#f1efe6' }, back: 'jetpack', eyes: '#4a3526', glow: '#ff8a4c' });
// companions (original ids kept)
hu('scout', 'Tess', 'DETECTIVE', 'Follows every lead until it ends.', 'scan', { body: 'feminine', build: 'slim', skin: SK[1], eyes: '#3f7a4a', hair: { style: 'ponytail', color: '#a5733f' }, top: { type: 'jacket', color: '#f1efe6', accent: '#ffe600' }, bottom: { type: 'pants', color: '#2b3a33' }, shoes: { type: 'boot', color: '#3a2a22' }, face: 'glasses', back: 'backpack', glow: '#ffe600' });
hu('maker', 'Fitz', 'CRAFTSMAN', 'Carries a whole workshop in his head.', 'orb', { body: 'masculine', build: 'broad', skin: SK[4], eyes: '#4a3526', hair: { style: 'buzz', color: '#1b1512' }, top: { type: 'tee', color: '#b7a1ef', accent: '#ffe600' }, bottom: { type: 'cargo', color: '#b7a1ef' }, shoes: { type: 'boot', color: '#2a302c' }, head: 'cap', glow: '#ffe600' });
hu('guardian', 'Greta', 'WARDEN', 'Stands between your work and what could break it.', 'shield', { body: 'feminine', build: 'broad', skin: SK[5], eyes: '#5a5a66', hair: { style: 'bun', color: '#1b1512' }, top: { type: 'bomber', color: '#e3ebe8', accent: '#7487a8' }, bottom: { type: 'pants', color: '#7487a8' }, shoes: { type: 'boot', color: '#2a302c' }, face: 'shades', glow: '#ffe600' });

/* The parametric body of each human (lib/harvex3d/src/e2c-sim.js): which hair, outfit and shoes of the asset pack it
   wears and what sets its body and face apart (shape numbers 0..1, detail sliders -1..1 on top of the house style).
   A saved agent's own `look.sim` is merged over this. */
const SIM = {
  atlas: { hair: 'short04', outfit: 'male_elegantsuit01', shoes: 'shoes01', muscle: 0.62, sliders: { jaw: 0.3, chinWidth: 0.25, browHeight: -0.2, shoulders: 0.2 } },
  nova: { hair: 'short02', outfit: 'female_casualsuit01', shoes: 'shoes05', sliders: { eyeSize: 0.2, lipUpper: 0.2, cheeks: 0.2, noseTip: 0.3 } },
  orbit: { hair: 'short04', outfit: 'male_worksuit01', shoes: 'shoes03', sliders: { noseWidth: 0.25, chinHeight: 0.15, eyeSpace: 0.15 } },
  kira: { hair: 'long01', outfit: 'female_elegantsuit01', shoes: 'shoes03', sliders: { eyeSlant: 0.35, chinHeight: -0.2, cheekbones: 0.25 } },
  dash: { hair: 'short01', outfit: 'male_casualsuit02', shoes: 'shoes06', muscle: 0.72, sliders: { jaw: 0.2, mouthWidth: 0.25, browAngle: 0.2 } },
  echo: { hair: 'short02', outfit: 'female_casualsuit01', shoes: 'shoes05', sliders: { cheeks: 0.35, eyeSize: 0.15, mouthCorners: 0.3 } },
  terra: { hair: 'short02', outfit: 'male_casualsuit05', shoes: 'shoes03', age: 0.3, sliders: { noseLength: 0.25, browAngle: -0.2, jaw: 0.15 } },
  volt: { hair: 'short01', outfit: 'male_casualsuit04', shoes: 'shoes03', muscle: 0.9, weight: 0.55, sliders: { jaw: 0.35, chinWidth: 0.3, neck: 0.4, shoulders: 0.4 } },
  vesper: { hair: 'afro01', outfit: 'female_casualsuit01', shoes: 'shoes05', sliders: { lipLower: 0.3, noseWidth: 0.3, cheekbones: 0.2 } },
  rook: { hair: 'short01', outfit: 'male_casualsuit02', shoes: 'shoes06', sliders: { browHeight: -0.3, jaw: 0.3, mouthCorners: -0.2 } },
  mira: { hair: 'long01', outfit: 'female_casualsuit01', shoes: 'shoes04', sliders: { eyeSpace: 0.2, mouthCorners: 0.3, noseTip: 0.25 } },
  juno: { hair: 'ponytail01', outfit: 'female_elegantsuit01', shoes: 'shoes04', sliders: { cheekbones: 0.35, chinWidth: -0.2, browAngle: 0.25 } },
  cole: { hair: 'short02', outfit: 'male_casualsuit06', shoes: 'shoes06', weight: 0.6, sliders: { noseWidth: 0.3, chinForward: 0.2, faceFat: 0.2 } },
  lumi: { hair: 'long01', outfit: 'female_elegantsuit01', shoes: 'shoes05', sliders: { eyeSize: 0.3, noseTip: 0.3, chinHeight: -0.15 } },
  otto: { hair: 'afro01', outfit: 'male_casualsuit05', shoes: 'shoes03', weight: 0.66, sliders: { cheeks: 0.4, faceFat: 0.35, noseWidth: 0.2 } },
  wren: { hair: 'long01', outfit: 'female_casualsuit02', shoes: 'shoes04', sliders: { eyeSlant: 0.4, eyeSize: 0.2, chinWidth: -0.25 } },
  zara: { hair: 'short04', outfit: 'female_sportsuit01', shoes: 'shoes05', muscle: 0.7, sliders: { jaw: 0.1, lipUpper: 0.3, cheekbones: 0.3 } },
  felix: { hair: 'short02', outfit: 'male_casualsuit04', shoes: 'shoes06', weight: 0.4, muscle: 0.38, sliders: { chinHeight: 0.2, noseLength: 0.2, ears: 0.3, jaw: -0.15 } },
  ines: { hair: 'ponytail01', outfit: 'female_elegantsuit01', shoes: 'shoes03', age: 0.35, sliders: { browHeight: 0.2, mouthWidth: -0.2, noseLength: 0.15 } },
  taro: { hair: 'short01', outfit: 'male_casualsuit05', shoes: 'shoes06', sliders: { eyeSlant: 0.3, noseWidth: 0.1, cheeks: 0.2 } },
  byte: { hair: 'short04', outfit: 'male_casualsuit02', shoes: 'shoes06', weight: 0.42, sliders: { eyeSize: 0.2, chinHeight: 0.15, browHeight: 0.2, ears: 0.2 } },
  scout: { hair: 'ponytail01', outfit: 'male_casualsuit05', shoes: 'shoes03', sliders: { eyeSize: 0.25, noseTip: 0.3, mouthCorners: 0.3, chinWidth: -0.2 } },
  maker: { hair: 'short01', outfit: 'male_worksuit01', shoes: 'shoes03', muscle: 0.8, weight: 0.6, sliders: { jaw: 0.3, noseWidth: 0.25, cheeks: 0.2, neck: 0.3 } },
  guardian: { hair: 'braid01', outfit: 'male_casualsuit05', shoes: 'shoes03', muscle: 0.75, height: 0.7, sliders: { jaw: 0.2, browHeight: -0.25, cheekbones: 0.3, shoulders: 0.3 } },
  noor: { hair: 'braid01', outfit: 'female_sportsuit01', shoes: 'shoes05', muscle: 0.66, sliders: { browAngle: 0.2, cheekbones: 0.3, lipLower: 0.2 } },
};
for (const p of P) if (SIM[p.id]) p.look.sim = SIM[p.id];
R.PRESETS = P;
R.getPreset = id => P.find(p => p.id === id) || P[0];

/* motions shown in the deck */
R.MOTION_GROUPS = [
  ['Gestures', ['Wave', 'Nod', 'Shrug', 'Point', 'Clap', 'Salute', 'Bow']],
  ['Moods', ['Idle', 'Think', 'Typing', 'Laugh', 'Cheer', 'Stretch', 'Victory']],
  ['Moves', ['Walk', 'Run', 'Jump', 'Spin', 'Dance', 'Disco']],
  ['Emotes', ['Flex', 'Heart', 'Dab', 'Facepalm', 'Kick', 'Backflip']],
  ['Life', ['Chat', 'Sit', 'Crouch', 'Pickup', 'Use', 'Tinker', 'Cast']],
];

/* power skills (character actions) */
R.POWERS = [
  { id: 'orb', name: 'Pulse Orb', key: '1', cd: 4, desc: 'Charges an energy orb between the hands and launches it.' },
  { id: 'shield', name: 'Aegis', key: '2', cd: 6, desc: 'Raises a hex shield dome around the agent.' },
  { id: 'blink', name: 'Blink', key: '3', cd: 5, desc: 'Dissolves and re-forms a step to the side.' },
  { id: 'levitate', name: 'Levitate', key: '4', cd: 7, desc: 'Floats above the pad with a ring of light.' },
  { id: 'scan', name: 'Deep Scan', key: '5', cd: 5, desc: 'Sweeps a scanner ring and reads the agent profile.' },
  { id: 'hype', name: 'Hype', key: '6', cd: 3, desc: 'Confetti burst and a cheer.' },
];
})(G);
}
export const HARVEX_DATA = (() => { const G = { HARVEX: {} }; installData(G); return G.HARVEX; })();
