/* GENERATED by scripts/render-page-cards.mjs: the link-preview cards that exist as files (public/og/<key>.png).
   The value is a mark of the file's content and goes into the picture's address. CARD_STAMP is the mark of what the
   cards were drawn from; `npm run build` compares it and draws the cards again when it no longer fits. */
export const CARD_STAMP='eb8b8ca13859b57a';
export const CARD_FILES={
 rewards:'67d272d553',
 schedules:'58c44c8e8b',
 skills:'0f4753e0e6',
 studio:'d87fa058da',
 quests:'2ada938049',
 tiers:'fea9aa7384',
 recipes:'c7b6f8a228',
 verified:'a74de4a082',
 plaza:'581b23f8bb',
 top:'4f888f456e',
 arena:'7c88e40d40',
 creators:'7c26375995',
 teams:'3925f0c1e8',
 invite:'201045d5c7',
 referral:'688c6e78ea',
 discover:'05a9d96938',
} as const;
