/* GENERATED by scripts/render-page-cards.mjs: the link-preview cards that exist as files (public/og/<key>.png).
   The value is a mark of the file's content and goes into the picture's address. CARD_STAMP is the mark of what the
   cards were drawn from; `npm run build` compares it and draws the cards again when it no longer fits. */
export const CARD_STAMP='5f87b66b2a6970af';
export const CARD_FILES={
 rewards:'67d272d553',
 schedules:'58c44c8e8b',
 skills:'0f4753e0e6',
 studio:'d87fa058da',
 quests:'2ada938049',
 tiers:'fea9aa7384',
 recipes:'c7b6f8a228',
 verified:'1a109c2133',
 plaza:'58b24ec976',
 top:'3b19f51ddf',
 arena:'f8c077d17f',
 creators:'8007908b8e',
 teams:'20a3d5f11f',
 invite:'201045d5c7',
 referral:'688c6e78ea',
 discover:'1e6a6ae91c',
} as const;
